export type DemoAttribute = "BATTERY_HOURS" | "ANC_LEVEL" | "BASS" | "COMFORT" | "MICROPHONE" | "WATER_RESISTANCE";

export type ProductSpecs = {
  batteryHours?: number;
  weightGrams?: number;
  waterRating?: string;
  bluetoothVersion?: string;
  driverSizeMm?: number;
  ancType?: string;
};

export type DemoProduct = {
  sku: string;
  name: string;
  brand: string;
  description: string;
  pricePaise: bigint;
  availableQty: number;
  category: "earbuds" | "headphones" | "speakers" | string;
  subcategory?: string;
  rating?: number;
  reviewCount?: number;
  useCases?: string[];
  features?: string[];
  specs?: ProductSpecs;
  attributes: Record<DemoAttribute, number>;
};

export const demoMerchant = { name: "SoundNest Electronics", slug: "soundnest-electronics" } as const;

export const demoCatalog: DemoProduct[] = [
  // ==========================================
  // EARBUDS (9 Products)
  // ==========================================
  {
    sku: "SN-BUDS-LITE",
    name: "SoundNest Buds Lite",
    brand: "SoundNest",
    description: "Lightweight daily true wireless earbuds with clear voice pickup and compact pocketable case.",
    pricePaise: 149900n,
    availableQty: 18,
    category: "earbuds",
    subcategory: "Daily True Wireless",
    rating: 4.3,
    reviewCount: 850,
    useCases: ["daily commute", "calls", "casual listening"],
    features: ["Clear Voice Mic", "Touch Controls", "Pocket Case", "Fast Pairing"],
    specs: { batteryHours: 24, weightGrams: 38, waterRating: "IPX4", bluetoothVersion: "5.3" },
    attributes: { BATTERY_HOURS: 65, ANC_LEVEL: 25, BASS: 60, COMFORT: 90, MICROPHONE: 72, WATER_RESISTANCE: 55 },
  },
  {
    sku: "SN-BUDS-COMFORT",
    name: "SoundNest Buds Comfort",
    brand: "SoundNest",
    description: "Ultra-slim ergonomic silicone design engineered for zero ear fatigue during all-day wear and bedtime.",
    pricePaise: 159900n,
    availableQty: 14,
    category: "earbuds",
    subcategory: "Ergonomic Daily Earbuds",
    rating: 4.7,
    reviewCount: 1100,
    useCases: ["all day wear", "bedtime", "audiobooks", "casual listening"],
    features: ["Featherweight Fit", "Pressure-Relief Vents", "Soft-Touch Finish", "Side-Sleep Friendly"],
    specs: { batteryHours: 22, weightGrams: 32, waterRating: "IPX4", bluetoothVersion: "5.3" },
    attributes: { BATTERY_HOURS: 62, ANC_LEVEL: 30, BASS: 64, COMFORT: 98, MICROPHONE: 74, WATER_RESISTANCE: 50 },
  },
  {
    sku: "SN-BUDS-ENDURE",
    name: "SoundNest Buds Endure",
    brand: "SoundNest",
    description: "Massive 50-hour total battery reserve with fast charge and rugged IPX7 waterproof casing.",
    pricePaise: 169900n,
    availableQty: 21,
    category: "earbuds",
    subcategory: "Long-Battery Earbuds",
    rating: 4.4,
    reviewCount: 730,
    useCases: ["long travel", "camping", "workouts", "daily commute"],
    features: ["50h Total Playtime", "IPX7 Waterproof", "10-Min Fast Charge", "Power Indicator"],
    specs: { batteryHours: 50, weightGrams: 48, waterRating: "IPX7", bluetoothVersion: "5.3" },
    attributes: { BATTERY_HOURS: 96, ANC_LEVEL: 20, BASS: 68, COMFORT: 75, MICROPHONE: 66, WATER_RESISTANCE: 92 },
  },
  {
    sku: "SN-BUDS-BASS",
    name: "SoundNest Buds Bass",
    brand: "SoundNest",
    description: "Punchy 12mm dynamic bass drivers engineered for workout motivation and high-energy music.",
    pricePaise: 179900n,
    availableQty: 12,
    category: "earbuds",
    subcategory: "Bass-Tuned True Wireless",
    rating: 4.5,
    reviewCount: 1420,
    useCases: ["workouts", "commuting", "gym", "bass music"],
    features: ["Extra Bass Boost", "IPX5 Sweatproof", "Low Latency Mode", "Snug Fit"],
    specs: { batteryHours: 28, weightGrams: 42, waterRating: "IPX5", bluetoothVersion: "5.3", driverSizeMm: 12 },
    attributes: { BATTERY_HOURS: 74, ANC_LEVEL: 35, BASS: 94, COMFORT: 70, MICROPHONE: 68, WATER_RESISTANCE: 78 },
  },
  {
    sku: "SN-BUDS-CLEAR",
    name: "SoundNest Buds Clear",
    brand: "SoundNest",
    description: "Quad-mic ENC array with AI environmental noise reduction designed specifically for crisp conference calls.",
    pricePaise: 189900n,
    availableQty: 9,
    category: "earbuds",
    subcategory: "Call-Centric True Wireless",
    rating: 4.6,
    reviewCount: 960,
    useCases: ["calls", "remote work", "zoom", "office"],
    features: ["AI Quad Mics", "ENC Call Clarification", "Multipoint Connect", "Fast Charge"],
    specs: { batteryHours: 30, weightGrams: 40, waterRating: "IPX4", bluetoothVersion: "5.3" },
    attributes: { BATTERY_HOURS: 70, ANC_LEVEL: 45, BASS: 58, COMFORT: 82, MICROPHONE: 95, WATER_RESISTANCE: 60 },
  },
  {
    sku: "SN-BUDS-QUIET",
    name: "SoundNest Buds Quiet",
    brand: "SoundNest",
    description: "35dB Active Noise Cancellation with Transparency Mode, isolating noisy metro rides and office chatter.",
    pricePaise: 199900n,
    availableQty: 16,
    category: "earbuds",
    subcategory: "Active Noise Cancelling Earbuds",
    rating: 4.6,
    reviewCount: 1850,
    useCases: ["travel", "commuting", "study", "office"],
    features: ["35dB ANC", "Transparency Mode", "Wireless Charging", "Ergonomic Stem"],
    specs: { batteryHours: 32, weightGrams: 44, waterRating: "IPX5", bluetoothVersion: "5.3", ancType: "35dB Hybrid ANC" },
    attributes: { BATTERY_HOURS: 76, ANC_LEVEL: 92, BASS: 76, COMFORT: 76, MICROPHONE: 78, WATER_RESISTANCE: 65 },
  },
  {
    sku: "SN-BUDS-ACTIVE",
    name: "SoundNest Buds Active Sport",
    brand: "SoundNest",
    description: "Sweat-guard IPX8 waterproof earbuds with flexible ear hooks for intense running and training.",
    pricePaise: 219900n,
    availableQty: 24,
    category: "earbuds",
    subcategory: "Sports Earbuds",
    rating: 4.6,
    reviewCount: 680,
    useCases: ["running", "gym", "workouts", "outdoor sports"],
    features: ["Secure Ear-Hooks", "IPX8 Submersible", "Punchy Sport EQ", "Physical Buttons"],
    specs: { batteryHours: 34, weightGrams: 52, waterRating: "IPX8", bluetoothVersion: "5.3" },
    attributes: { BATTERY_HOURS: 80, ANC_LEVEL: 25, BASS: 88, COMFORT: 78, MICROPHONE: 65, WATER_RESISTANCE: 98 },
  },
  {
    sku: "SN-BUDS-AIR",
    name: "SoundNest Buds OpenAir",
    brand: "SoundNest",
    description: "Open-ear directional acoustic design keeping you aware of traffic and surroundings with zero in-ear pressure.",
    pricePaise: 279900n,
    availableQty: 15,
    category: "earbuds",
    subcategory: "Open-Ear True Wireless",
    rating: 4.4,
    reviewCount: 420,
    useCases: ["outdoor running", "cycling", "office awareness", "commuting"],
    features: ["Open-Ear Awareness", "Directional Sound", "Lightweight Titanium Frame", "Dual Mics"],
    specs: { batteryHours: 26, weightGrams: 36, waterRating: "IPX5", bluetoothVersion: "5.3" },
    attributes: { BATTERY_HOURS: 72, ANC_LEVEL: 10, BASS: 62, COMFORT: 95, MICROPHONE: 80, WATER_RESISTANCE: 70 },
  },
  {
    sku: "SN-BUDS-PRO",
    name: "SoundNest Buds Pro",
    brand: "SoundNest",
    description: "Flagship dual-driver audio with 42dB Hybrid ANC, high-res LDAC decoding, and multipoint Bluetooth.",
    pricePaise: 399900n,
    availableQty: 11,
    category: "earbuds",
    subcategory: "Flagship ANC Earbuds",
    rating: 4.8,
    reviewCount: 2300,
    useCases: ["travel", "audiophile", "work", "commuting", "flights"],
    features: ["42dB Hybrid ANC", "LDAC Hi-Res Audio", "Multipoint Connect", "Spatial Audio", "Qi Wireless Charging"],
    specs: { batteryHours: 36, weightGrams: 46, waterRating: "IPX5", bluetoothVersion: "5.3", ancType: "42dB Adaptive ANC" },
    attributes: { BATTERY_HOURS: 84, ANC_LEVEL: 95, BASS: 85, COMFORT: 86, MICROPHONE: 88, WATER_RESISTANCE: 75 },
  },

  // ==========================================
  // HEADPHONES (8 Products)
  // ==========================================
  {
    sku: "SN-HP-KIDSAFE",
    name: "SoundNest JuniorSafe 100",
    brand: "SoundNest",
    description: "Durable kid-safe wireless headphones with 85dB volume limit, flexible headband, and fun sticker pack.",
    pricePaise: 129900n,
    availableQty: 18,
    category: "headphones",
    subcategory: "Kids Safe Volume Headphones",
    rating: 4.4,
    reviewCount: 320,
    useCases: ["kids", "online classes", "family travel", "audiobooks"],
    features: ["85dB Safe Volume Limiter", "Indestructible Flexible Band", "Sharing Audio Port", "25h Battery"],
    specs: { batteryHours: 25, weightGrams: 130, waterRating: "IPX4", bluetoothVersion: "5.2" },
    attributes: { BATTERY_HOURS: 68, ANC_LEVEL: 15, BASS: 50, COMFORT: 88, MICROPHONE: 60, WATER_RESISTANCE: 50 },
  },
  {
    sku: "SN-HP-BASSWAVE",
    name: "SoundNest BassWave 200",
    brand: "SoundNest",
    description: "Budget-friendly wireless over-ear headphones with deep 40mm bass drivers and 30-hour battery life.",
    pricePaise: 199900n,
    availableQty: 20,
    category: "headphones",
    subcategory: "Wireless Over-Ear",
    rating: 4.4,
    reviewCount: 2100,
    useCases: ["casual listening", "bass music", "commuting", "movies"],
    features: ["Bass Boost Button", "30h Playtime", "Padded Headband", "Foldable"],
    specs: { batteryHours: 30, weightGrams: 210, waterRating: "IPX4", bluetoothVersion: "5.2", driverSizeMm: 40 },
    attributes: { BATTERY_HOURS: 78, ANC_LEVEL: 20, BASS: 92, COMFORT: 80, MICROPHONE: 65, WATER_RESISTANCE: 30 },
  },
  {
    sku: "SN-HP-AIRLITE",
    name: "SoundNest AirLite 300",
    brand: "SoundNest",
    description: "Featherlight on-ear headphones weighing only 150g, perfect for daily commuting and walk-and-talk calls.",
    pricePaise: 249900n,
    availableQty: 14,
    category: "headphones",
    subcategory: "Lightweight Wireless Headphones",
    rating: 4.5,
    reviewCount: 780,
    useCases: ["commuting", "walking", "calls", "casual listening", "travel"],
    features: ["150g Ultralight", "Clear Voice Mic", "35h Battery", "Quick Charge"],
    specs: { batteryHours: 35, weightGrams: 150, waterRating: "IPX4", bluetoothVersion: "5.3" },
    attributes: { BATTERY_HOURS: 80, ANC_LEVEL: 30, BASS: 65, COMFORT: 90, MICROPHONE: 85, WATER_RESISTANCE: 45 },
  },
  {
    sku: "SN-HP-PULSE-GAME",
    name: "SoundNest Pulse Gaming 7.1",
    brand: "SoundNest",
    description: "Ultra-low latency wireless headset with 7.1 virtual surround sound and broadcast-grade boom mic.",
    pricePaise: 299900n,
    availableQty: 12,
    category: "headphones",
    subcategory: "Gaming Headset",
    rating: 4.5,
    reviewCount: 920,
    useCases: ["gaming", "discord calls", "streaming", "movies"],
    features: ["7.1 Surround Sound", "Detachable Boom Mic", "2.4GHz Low Latency Dongle", "RGB Lighting"],
    specs: { batteryHours: 32, weightGrams: 290, waterRating: "IPX3", bluetoothVersion: "5.3 / 2.4GHz" },
    attributes: { BATTERY_HOURS: 75, ANC_LEVEL: 35, BASS: 88, COMFORT: 85, MICROPHONE: 94, WATER_RESISTANCE: 20 },
  },
  {
    sku: "SN-HP-STUDIOPRO",
    name: "SoundNest StudioPro 500",
    brand: "SoundNest",
    description: "Neutral reference audio tuning for music production, podcasting, and critical audiophile listening.",
    pricePaise: 349900n,
    availableQty: 8,
    category: "headphones",
    subcategory: "Studio Monitor Headphones",
    rating: 4.6,
    reviewCount: 540,
    useCases: ["music production", "podcasting", "critical listening", "editing"],
    features: ["Flat Frequency Response", "50mm Neodymium Drivers", "Detachable Coiled Cable", "Swivel Earcups"],
    specs: { batteryHours: 40, weightGrams: 280, waterRating: "IPX3", bluetoothVersion: "5.3", driverSizeMm: 50 },
    attributes: { BATTERY_HOURS: 82, ANC_LEVEL: 40, BASS: 75, COMFORT: 88, MICROPHONE: 75, WATER_RESISTANCE: 25 },
  },
  {
    sku: "SN-HP-WAVE-ANC",
    name: "SoundNest Wave ANC 700",
    brand: "SoundNest",
    description: "Over-ear noise cancelling headphones with memory foam earcups, designed for deep focus and long flights.",
    pricePaise: 449900n,
    availableQty: 10,
    category: "headphones",
    subcategory: "Over-Ear ANC Headphones",
    rating: 4.7,
    reviewCount: 1640,
    useCases: ["travel", "long flights", "study", "commuting", "office"],
    features: ["Active Noise Cancelling", "Plush Memory Foam", "Foldable Design", "Aux Backup Cable"],
    specs: { batteryHours: 45, weightGrams: 240, waterRating: "IPX4", bluetoothVersion: "5.3", ancType: "Hybrid ANC" },
    attributes: { BATTERY_HOURS: 88, ANC_LEVEL: 94, BASS: 82, COMFORT: 94, MICROPHONE: 82, WATER_RESISTANCE: 40 },
  },
  {
    sku: "SN-HP-FLYMAX",
    name: "SoundNest FlyMax 900 Travel",
    brand: "SoundNest",
    description: "Ultimate travel companion featuring 65-hour marathon battery life, airplane adapter, and high-attenuation ANC.",
    pricePaise: 599900n,
    availableQty: 7,
    category: "headphones",
    subcategory: "Premium Travel Headphones",
    rating: 4.8,
    reviewCount: 890,
    useCases: ["long flights", "travel", "international travel", "remote work", "transit"],
    features: ["65h Battery", "Advanced Airplane ANC", "Airplane Adapter Included", "Hard Shell Travel Case", "Multipoint"],
    specs: { batteryHours: 65, weightGrams: 260, waterRating: "IPX4", bluetoothVersion: "5.3", ancType: "Adaptive Travel ANC" },
    attributes: { BATTERY_HOURS: 99, ANC_LEVEL: 97, BASS: 84, COMFORT: 96, MICROPHONE: 86, WATER_RESISTANCE: 35 },
  },
  {
    sku: "SN-HP-APEX-1000",
    name: "SoundNest Apex Wireless 1000",
    brand: "SoundNest",
    description: "Handcrafted premium aluminum headphones with planar magnetic sound stage and world-class noise cancelation.",
    pricePaise: 899900n,
    availableQty: 5,
    category: "headphones",
    subcategory: "Luxury Audiophile ANC",
    rating: 4.9,
    reviewCount: 410,
    useCases: ["travel", "luxury audiophile", "flights", "home listening"],
    features: ["Planar Magnetic Drivers", "Adaptive Smart ANC", "Lambskin Ear Cushions", "Hi-Res Audio LDAC"],
    specs: { batteryHours: 50, weightGrams: 275, waterRating: "IPX4", bluetoothVersion: "5.3", ancType: "Adaptive AI ANC" },
    attributes: { BATTERY_HOURS: 92, ANC_LEVEL: 98, BASS: 90, COMFORT: 98, MICROPHONE: 90, WATER_RESISTANCE: 35 },
  },

  // ==========================================
  // SPEAKERS (9 Products)
  // ==========================================
  {
    sku: "SN-SPK-SOUNDPUCK",
    name: "SoundNest SoundPuck Mini",
    brand: "SoundNest",
    description: "Affordable compact mini speaker with surprisingly clear vocal delivery and magnetic base.",
    pricePaise: 119900n,
    availableQty: 30,
    category: "speakers",
    subcategory: "Budget Mini Speaker",
    rating: 4.3,
    reviewCount: 1950,
    useCases: ["desk", "casual listening", "kitchen", "audiobooks"],
    features: ["Magnetic Base", "Ultra-Budget", "Compact Puck Design", "Aux & Bluetooth"],
    specs: { batteryHours: 10, weightGrams: 160, waterRating: "IPX4", bluetoothVersion: "5.1" },
    attributes: { BATTERY_HOURS: 62, ANC_LEVEL: 0, BASS: 55, COMFORT: 0, MICROPHONE: 50, WATER_RESISTANCE: 50 },
  },
  {
    sku: "SN-SPK-MICROGO",
    name: "SoundNest MicroGo Pocket",
    brand: "SoundNest",
    description: "Compact palm-sized bluetooth speaker with integrated clip loop, loud clean sound, and 12h playtime.",
    pricePaise: 149900n,
    availableQty: 25,
    category: "speakers",
    subcategory: "Ultra-Portable Pocket Speaker",
    rating: 4.4,
    reviewCount: 2800,
    useCases: ["travel", "cycling", "shower", "hiking", "pocket"],
    features: ["Pocket Size", "Integrated Clip Loop", "IP67 Dust & Water Proof", "12h Battery"],
    specs: { batteryHours: 12, weightGrams: 190, waterRating: "IP67", bluetoothVersion: "5.3" },
    attributes: { BATTERY_HOURS: 70, ANC_LEVEL: 0, BASS: 65, COMFORT: 0, MICROPHONE: 55, WATER_RESISTANCE: 95 },
  },
  {
    sku: "SN-SPK-BASSBOX20",
    name: "SoundNest BassBox 20",
    brand: "SoundNest",
    description: "Compact 20W cylinder speaker with dual side bass radiators and vibrant led ring for music on the go.",
    pricePaise: 239900n,
    availableQty: 16,
    category: "speakers",
    subcategory: "Portable Bass Speaker",
    rating: 4.5,
    reviewCount: 1310,
    useCases: ["parties", "daily listening", "room audio", "bass music"],
    features: ["20W Dual Radiators", "LED Ring Light", "IPX6 Splashproof", "14h Battery"],
    specs: { batteryHours: 14, weightGrams: 470, waterRating: "IPX6", bluetoothVersion: "5.3" },
    attributes: { BATTERY_HOURS: 75, ANC_LEVEL: 0, BASS: 90, COMFORT: 0, MICROPHONE: 58, WATER_RESISTANCE: 80 },
  },
  {
    sku: "SN-SPK-TOUGHSOUND",
    name: "SoundNest ToughSound IP67",
    brand: "SoundNest",
    description: "Drop-proof, dust-proof, and fully floatable IP67 outdoor speaker designed for beach trips and camping.",
    pricePaise: 289900n,
    availableQty: 14,
    category: "speakers",
    subcategory: "Rugged Outdoor Speaker",
    rating: 4.6,
    reviewCount: 940,
    useCases: ["outdoor", "beach", "camping", "hiking", "travel"],
    features: ["Floatable Waterproof", "Drop-Proof Rubber Bumper", "Carabiner Clip", "Powerbank Function"],
    specs: { batteryHours: 20, weightGrams: 520, waterRating: "IP67", bluetoothVersion: "5.3" },
    attributes: { BATTERY_HOURS: 85, ANC_LEVEL: 0, BASS: 84, COMFORT: 0, MICROPHONE: 62, WATER_RESISTANCE: 99 },
  },
  {
    sku: "SN-SPK-TREKKER360",
    name: "SoundNest Trekker 360",
    brand: "SoundNest",
    description: "Omnidirectional 360-degree acoustic dispersion with huge 30-hour battery reserve and outdoor boost mode.",
    pricePaise: 349900n,
    availableQty: 9,
    category: "speakers",
    subcategory: "360-Degree Long Battery Speaker",
    rating: 4.7,
    reviewCount: 760,
    useCases: ["long battery", "camping", "travel", "gatherings", "picnic"],
    features: ["30h Marathon Battery", "360-Degree Sound", "Outdoor Sound Boost", "Type-C Fast Charge"],
    specs: { batteryHours: 30, weightGrams: 590, waterRating: "IPX6", bluetoothVersion: "5.3" },
    attributes: { BATTERY_HOURS: 98, ANC_LEVEL: 0, BASS: 86, COMFORT: 0, MICROPHONE: 58, WATER_RESISTANCE: 85 },
  },
  {
    sku: "SN-SPK-BOOM500",
    name: "SoundNest BoomParty 500",
    brand: "SoundNest",
    description: "Dynamic party powerhouse with sync beat RGB lights, dedicated bass boost button, and rugged carry handle.",
    pricePaise: 379900n,
    availableQty: 11,
    category: "speakers",
    subcategory: "Party Speaker with Bass Boost",
    rating: 4.7,
    reviewCount: 1120,
    useCases: ["parties", "gatherings", "bbq", "bass music", "outdoor"],
    features: ["RGB Beat Lighting", "Bass Boost EQ", "Carry Handle", "Mic Input for Karaoke"],
    specs: { batteryHours: 16, weightGrams: 950, waterRating: "IPX5", bluetoothVersion: "5.3" },
    attributes: { BATTERY_HOURS: 78, ANC_LEVEL: 0, BASS: 96, COMFORT: 0, MICROPHONE: 68, WATER_RESISTANCE: 75 },
  },
  {
    sku: "SN-SPK-PRO",
    name: "SoundNest Speaker Pro",
    brand: "SoundNest",
    description: "Heavy-hitting 30W wireless speaker with dual passive bass radiators, room-filling sound, and IPX7 waterproofing.",
    pricePaise: 399900n,
    availableQty: 8,
    category: "speakers",
    subcategory: "High-Power Bluetooth Speaker",
    rating: 4.8,
    reviewCount: 1530,
    useCases: ["parties", "home audio", "outdoor", "bass music"],
    features: ["30W Bass Radiators", "IPX7 Waterproof", "TWS Stereo Pairing", "18h Battery"],
    specs: { batteryHours: 18, weightGrams: 680, waterRating: "IPX7", bluetoothVersion: "5.3" },
    attributes: { BATTERY_HOURS: 82, ANC_LEVEL: 0, BASS: 98, COMFORT: 0, MICROPHONE: 60, WATER_RESISTANCE: 90 },
  },
  {
    sku: "SN-SPK-STUDIOTONE",
    name: "SoundNest StudioTone 2.0",
    brand: "SoundNest",
    description: "Acoustic wood-enclosure desktop speaker delivering warm audiophile stereo sound, optical input, and Bluetooth.",
    pricePaise: 499900n,
    availableQty: 6,
    category: "speakers",
    subcategory: "Premium Desk Stereo Speaker",
    rating: 4.8,
    reviewCount: 620,
    useCases: ["desk", "home audio", "turntable", "bookshelf"],
    features: ["Real Wood Enclosure", "Dual Silk Dome Tweeters", "Optical & RCA Inputs", "Treble/Bass Knobs"],
    specs: { batteryHours: 24, weightGrams: 1400, waterRating: "IPX2", bluetoothVersion: "5.3" },
    attributes: { BATTERY_HOURS: 84, ANC_LEVEL: 0, BASS: 92, COMFORT: 0, MICROPHONE: 50, WATER_RESISTANCE: 20 },
  },
  {
    sku: "SN-SPK-CINEMABAR",
    name: "SoundNest CinemaBar 120",
    brand: "SoundNest",
    description: "Slim 120W soundbar with built-in subwoofer, HDMI eARC, and dedicated movie/dialogue sound modes.",
    pricePaise: 649900n,
    availableQty: 5,
    category: "speakers",
    subcategory: "Home Theater Soundbar",
    rating: 4.7,
    reviewCount: 480,
    useCases: ["tv", "movies", "home theater", "living room"],
    features: ["120W Peak Power", "Built-in Subwoofer", "HDMI eARC & Optical", "Dolby Audio Decoding"],
    specs: { batteryHours: 0, weightGrams: 2200, waterRating: "IPX0", bluetoothVersion: "5.3" },
    attributes: { BATTERY_HOURS: 0, ANC_LEVEL: 0, BASS: 95, COMFORT: 0, MICROPHONE: 40, WATER_RESISTANCE: 10 },
  },
];
